import Testing
@testable import ClipboardKit

private func snapshot(types: [String], from bundleID: String? = "com.apple.TextEdit") -> PasteboardSnapshot {
    PasteboardSnapshot(types: types, sourceBundleID: bundleID)
}

@Test("обычный текст из обычного приложения попадает в историю")
func plainTextIsCaptured() {
    let filter = PrivacyFilter()
    #expect(filter.shouldCapture(snapshot(types: ["public.utf8-plain-text"])))
}

@Test("флаг ConcealedType отменяет захват — его ставят менеджеры паролей")
func concealedTypeIsRejected() {
    let filter = PrivacyFilter()
    #expect(filter.shouldCapture(snapshot(types: [
        "public.utf8-plain-text", PasteboardType.concealed
    ])) == false)
}

@Test("временное содержимое не сохраняется")
func transientTypeIsRejected() {
    let filter = PrivacyFilter()
    #expect(filter.shouldCapture(snapshot(types: [
        "public.utf8-plain-text", PasteboardType.transient
    ])) == false)
}

@Test("автосгенерированное содержимое не сохраняется")
func autoGeneratedTypeIsRejected() {
    let filter = PrivacyFilter()
    #expect(filter.shouldCapture(snapshot(types: [
        "public.utf8-plain-text", PasteboardType.autoGenerated
    ])) == false)
}

@Test("копирование из менеджера паролей отсекается по приложению-источнику")
func blockedAppIsRejected() {
    let filter = PrivacyFilter()
    for blocked in PrivacyFilter.defaultBlockedBundleIDs {
        #expect(filter.shouldCapture(snapshot(types: ["public.utf8-plain-text"], from: blocked)) == false)
    }
}

@Test("чёрный список настраивается")
func customBlockListIsHonoured() {
    let filter = PrivacyFilter(blockedBundleIDs: ["com.example.secrets"])
    #expect(filter.shouldCapture(snapshot(types: ["public.utf8-plain-text"], from: "com.example.secrets")) == false)
    // Свой список заменяет умолчания целиком, а не дополняет: иначе
    // отключить встроенную запись было бы нечем.
    #expect(filter.shouldCapture(snapshot(types: ["public.utf8-plain-text"], from: "com.1password.1password")))
}

@Test("неизвестный источник не повод отказывать")
func unknownSourceIsAllowed() {
    let filter = PrivacyFilter()
    #expect(filter.shouldCapture(snapshot(types: ["public.utf8-plain-text"], from: nil)))
}

@Test("пустой пастборд не событие")
func emptyTypesAreRejected() {
    let filter = PrivacyFilter()
    #expect(filter.shouldCapture(snapshot(types: [])) == false)
}
