import Testing
@testable import ClipboardKit

private func snapshot(types: [String], from bundleID: String? = "com.apple.TextEdit") -> PasteboardSnapshot {
    PasteboardSnapshot(types: types, sourceBundleID: bundleID)
}

@Test("plain text from a regular app makes it into history")
func plainTextIsCaptured() {
    let filter = PrivacyFilter()
    #expect(filter.shouldCapture(snapshot(types: ["public.utf8-plain-text"])))
}

@Test("the ConcealedType flag cancels capture — password managers set it")
func concealedTypeIsRejected() {
    let filter = PrivacyFilter()
    #expect(filter.shouldCapture(snapshot(types: [
        "public.utf8-plain-text", PasteboardType.concealed
    ])) == false)
}

@Test("transient content is not saved")
func transientTypeIsRejected() {
    let filter = PrivacyFilter()
    #expect(filter.shouldCapture(snapshot(types: [
        "public.utf8-plain-text", PasteboardType.transient
    ])) == false)
}

@Test("auto-generated content is not saved")
func autoGeneratedTypeIsRejected() {
    let filter = PrivacyFilter()
    #expect(filter.shouldCapture(snapshot(types: [
        "public.utf8-plain-text", PasteboardType.autoGenerated
    ])) == false)
}

@Test("copying from a password manager is blocked by source app")
func blockedAppIsRejected() {
    let filter = PrivacyFilter()
    // The loop below iterates over the same constant it checks, and a test with
    // no #expect calls still counts as passing. A list emptied by oversight
    // would yield zero iterations and a green test with protection removed, so
    // there's an independent check here.
    #expect(PrivacyFilter.defaultBlockedBundleIDs.contains("com.1password.1password"))

    for blocked in PrivacyFilter.defaultBlockedBundleIDs {
        #expect(filter.shouldCapture(snapshot(types: ["public.utf8-plain-text"], from: blocked)) == false)
    }
}

@Test("case in the app identifier does not open a loophole")
func blockedAppIsRejectedRegardlessOfCase() {
    let filter = PrivacyFilter()
    #expect(filter.shouldCapture(snapshot(types: ["public.utf8-plain-text"], from: "com.1Password.1Password")) == false)

    // And the other way around: a list given in uppercase must
    // catch a source that comes in lowercase.
    let shouting = PrivacyFilter(blockedBundleIDs: ["COM.EXAMPLE.SECRETS"])
    #expect(shouting.shouldCapture(snapshot(types: ["public.utf8-plain-text"], from: "com.example.secrets")) == false)
}

@Test("the block list is configurable")
func customBlockListIsHonoured() {
    let filter = PrivacyFilter(blockedBundleIDs: ["com.example.secrets"])
    #expect(filter.shouldCapture(snapshot(types: ["public.utf8-plain-text"], from: "com.example.secrets")) == false)
    // A custom list replaces the defaults entirely rather than extending them —
    // otherwise there'd be no way to turn off the built-in entry.
    #expect(filter.shouldCapture(snapshot(types: ["public.utf8-plain-text"], from: "com.1password.1password")))
}

@Test("an unknown source is not a reason to reject")
func unknownSourceIsAllowed() {
    let filter = PrivacyFilter()
    #expect(filter.shouldCapture(snapshot(types: ["public.utf8-plain-text"], from: nil)))
}

@Test("an empty pasteboard is not an event")
func emptyTypesAreRejected() {
    let filter = PrivacyFilter()
    #expect(filter.shouldCapture(snapshot(types: [])) == false)
}
