import Foundation

/// Pasteboard type identifiers that matter for privacy.
///
/// This isn't an Apple UTI, but a convention followed by password managers:
/// an app tags its content so that clipboard managers won't store it.
/// Honoring it is a matter of decency, not compatibility.
public enum PasteboardType {
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let transient = "org.nspasteboard.TransientType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
}

/// What's read from the pasteboard, without AppKit.
///
/// Deliberately decoupled from `NSPasteboard`: filtering and parsing should
/// be testable against made-up combinations of types, not against a machine's
/// live pasteboard, where a password manager's flag can't be reproduced.
public struct PasteboardSnapshot: Sendable, Equatable {
    public let types: [String]
    public let sourceBundleID: String?

    public init(types: [String], sourceBundleID: String?) {
        self.types = types
        self.sourceBundleID = sourceBundleID
    }
}
