import Foundation

/// Идентификаторы типов пастборда, важные для приватности.
///
/// Это не UTI Apple, а конвенция, которой следуют менеджеры паролей:
/// приложение помечает содержимое, чтобы менеджеры буфера его не сохраняли.
/// Соблюдать её — вопрос не совместимости, а порядочности.
public enum PasteboardType {
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let transient = "org.nspasteboard.TransientType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
}

/// То, что прочитано из пастборда, без AppKit.
///
/// Отделено от `NSPasteboard` намеренно: фильтры и разбор должны
/// проверяться на выдуманных сочетаниях типов, а не на живом пастборде
/// машины, где нельзя воспроизвести флаг менеджера паролей.
public struct PasteboardSnapshot: Sendable, Equatable {
    public let types: [String]
    public let sourceBundleID: String?

    public init(types: [String], sourceBundleID: String?) {
        self.types = types
        self.sourceBundleID = sourceBundleID
    }
}
