import Foundation

/// Решает, попадает ли скопированное в историю.
///
/// Три слоя, потому что ни один не полон: флаг ставят не все менеджеры
/// паролей, чёрный список не знает про приложения, о которых мы не подумали,
/// а временные типы ловят автоматику вроде переводчиков и сокращателей
/// ссылок. Вместе они дают приемлемый уровень, порознь — нет.
public struct PrivacyFilter: Sendable {
    /// Приложения, копирование из которых не сохраняется никогда.
    public static let defaultBlockedBundleIDs: Set<String> = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.apple.keychainaccess",
    ]

    private static let rejectedTypes: Set<String> = [
        PasteboardType.concealed,
        PasteboardType.transient,
        PasteboardType.autoGenerated,
    ]

    private let blockedBundleIDs: Set<String>

    public init(blockedBundleIDs: Set<String> = PrivacyFilter.defaultBlockedBundleIDs) {
        self.blockedBundleIDs = blockedBundleIDs
    }

    public func shouldCapture(_ snapshot: PasteboardSnapshot) -> Bool {
        guard !snapshot.types.isEmpty else { return false }
        guard snapshot.types.allSatisfy({ !Self.rejectedTypes.contains($0) }) else { return false }
        // Неизвестный источник не повод отказывать: bundle id пропадает,
        // например, при копировании из системных диалогов, и терять из-за
        // этого обычный текст было бы хуже, чем сохранить его.
        guard let source = snapshot.sourceBundleID else { return true }
        return !blockedBundleIDs.contains(source)
    }
}
