import Foundation

/// Decides whether a copied item makes it into the history.
///
/// Three layers, because none of them is complete on its own: not every
/// password manager sets the flag, the blocklist doesn't know about apps we
/// didn't think of, and transient types catch automation like translators
/// and link shorteners. Together they give an acceptable level; apart, they
/// don't.
public struct PrivacyFilter: Sendable {
    /// Apps whose copies are never saved.
    public static let defaultBlockedBundleIDs: Set<String> = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.apple.keychainaccess",
    ]

    private static let rejectedTypes: Set<String> = [
        PasteboardType.concealed,
        PasteboardType.transient,
        PasteboardType.autoGenerated,
    ]

    /// The list is stored lowercased, and comparisons go against that same form.
    ///
    /// The system treats app bundle IDs as case-insensitive, but exact string
    /// comparison is case-sensitive: `com.1Password.1Password` and
    /// `com.1password.1password` would end up as different apps, and a password
    /// manager that reported itself in the wrong case would sail straight
    /// through the filter. The error here is asymmetric — an unnecessary
    /// rejection costs a lost history entry, a miss costs a password on disk —
    /// so we normalize instead of relying on vendor consistency.
    private let blockedBundleIDs: Set<String>

    public init(blockedBundleIDs: Set<String> = PrivacyFilter.defaultBlockedBundleIDs) {
        self.blockedBundleIDs = Set(blockedBundleIDs.map { $0.lowercased() })
    }

    public func shouldCapture(_ snapshot: PasteboardSnapshot) -> Bool {
        guard !snapshot.types.isEmpty else { return false }
        guard snapshot.types.allSatisfy({ !Self.rejectedTypes.contains($0) }) else { return false }
        // An unknown source isn't a reason to reject: the bundle id disappears,
        // for example, when copying from system dialogs, and losing ordinary
        // text because of that would be worse than keeping it.
        guard let source = snapshot.sourceBundleID else { return true }
        return !blockedBundleIDs.contains(source.lowercased())
    }
}
